### ISSUE TITLE
FileList not respecting prefix_jobid on HPC cluster

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-dashboard#127]
### Description

I'm running a dashboard on a compute node on the PSC bridges2 cluster. I've added a `FileList` instance to my list of modules, and have explicitly set `prefix_jobid=True` on construction of the module. In the dashboard, when I click on a filename to download, the job id is not being prepended to the name of the file to download.

### To reproduce

I launch the dashboard with ` python dashboard.py run --port=8889 --host=0.0.0.0`. A minimal version of my dashboard script is:
```python
from signac_dashboard import Dashboard
from signac_dashboard.modules import FileList

class PlotDashboard(Dashboard):
    pass

if __name__ == '__main__':
    filelist = FileList(prefix_jobid=True)
    PlotDashboard(modules=[filelist]).main()
```

I cannot reproduce this error on my local machine. Running that script with both ` python dashboard.py run --port=8889 --host=0.0.0.0` and ` python dashboard.py run --port=8889` yields the expected behavior. I also cannot reproduce remotely on a mac mini.

### System configuration
Bridges2:
```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac_dashboard; print(signac_dashboard.__version__)'
Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-glibc2.28
3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]
0.2.10
```

Local machine:
```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac_dashboard; print(signac_dashboard.__version__)'
Darwin-20.6.0-x86_64-i386-64bit
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ]
0.2.9
```

mac mini:
```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac_dashboard; print(signac_dashboard.__version__)'
Darwin-17.7.0-x86_64-i386-64bit
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23) 
[Clang 11.1.0 ]
0.2.9
```

**Comment by tcmoore3** [comment]
I just noticed that I have different versions on my local machine and on the cluster. When I run with the latest version 0.2.10 on `conda-forge` on my laptop, I do get the same error. Investigating.

**Comment by tcmoore3** [comment]
I can confirm that the html is being rendered correctly, e.g., the list items in the html are:
```
<li><a href="/jobs/ff21ddedfb05cf189c6e0ff2f4a40192/file/traj.gsd" download="ff21ddedfb05cf189c6e0ff2f4a40192_traj.gsd">traj.gsd</a></li>
```

**Comment by b-butler** [comment]
Then updating dashboard would not lead to the error occurring or not.

**Comment by tcmoore3** [comment]
When I save the source of the rendered html files, the only differences appear to be related to the stylesheets, the port each dashboard was running on, and the version of `signac-dashboard`.

```
$ diff view-source_localhost_8888_jobs__view\=grid.html view-source_localhost_8889_jobs__view\=grid.html 
7c7
<         <link rel="stylesheet" href="/static/gen/app.css?158ab2f6">
---
>         <link rel="stylesheet" href="/static/gen/app.css?e147bbb1">
57c57
<                             <input type="hidden" name="redirect" value="http://localhost:8888/jobs/?view=grid">
---
>                             <input type="hidden" name="redirect" value="http://localhost:8889/jobs/?view=grid">
136c136
<                             <input type="hidden" name="redirect" value="http://localhost:8888/jobs/?view=grid">
---
>                             <input type="hidden" name="redirect" value="http://localhost:8889/jobs/?view=grid">
954c954
<                     <p><strong>signac-dashboard 0.2.9</strong> by <a href="https://glotzerlab.engin.umich.edu">the Glotzer Group</a></p>
---
>                     <p><strong>signac-dashboard 0.2.10</strong> by <a href="https://glotzerlab.engin.umich.edu">the Glotzer Group</a></p>
```

**Comment by tcmoore3** [comment]
The issue is not caused by any changes to the `signac-dashboard` codebase, but is caused by changes to `werkzeug`. The differences I was seeing earlier were caused by the fact that I had two different environments I was testing the different versions with. My environment with dashboard 0.2.9 had a very old version of `werkzeug`, whereas my environment with dashboard 0.2.10 had the latest version. When I updated werkzeug in my 0.2.9 environment, I get the same behavior.

**Comment by tcmoore3** [comment]
When I showed this to @joaander , he suggested I view the headers of the link target. It appears that the `Content-Disposition` header is being set, and the filename is just the filename without the prepended job id: 
```bash
$ curl -I http://localhost:8888/jobs/35478bb1cef990f56fd7a37abe2f88a5/file/energy-plot-timesteps.txt
HTTP/1.0 200 OK
Content-Disposition: inline; filename=energy-plot-timesteps.txt
Content-Type: text/plain; charset=utf-8
Content-Length: 17
Last-Modified: Thu, 21 Apr 2022 13:43:24 GMT
Cache-Control: no-cache, max-age=0
Expires: Thu, 21 Apr 2022 21:37:44 GMT
Date: Thu, 21 Apr 2022 21:37:44 GMT
Server: Werkzeug/2.0.3 Python/3.9.12
```

When I set `as_attachment=True` in `views.get_file()`, the `Content-Disposition` value changes:
```bash
$ curl -I http://localhost:8888/jobs/35478bb1cef990f56fd7a37abe2f88a5/file/energy-plot-timesteps.txt
HTTP/1.0 200 OK
Content-Disposition: attachment; filename=energy-plot-timesteps.txt
Content-Type: text/plain; charset=utf-8
Content-Length: 17
Last-Modified: Thu, 21 Apr 2022 13:43:24 GMT
Cache-Control: no-cache, max-age=0
Expires: Thu, 21 Apr 2022 21:37:44 GMT
Date: Thu, 21 Apr 2022 21:37:44 GMT
Server: Werkzeug/2.0.3 Python/3.9.12
```

**Comment by cbkerr** [comment]
>In the dashboard, when I click on a filename to download, the job id is not being prepended to the name of the file to download

Since this is no longer the symptom, what is the actual unexpected behavior that you observe?
It's not clear if you want Content-Disposition to be inline or attachment.

Does it work in Chrome?
Searching https://caniuse.com/?search=Content-Disposition led me to the footnote for Firefox that "From version 82, if an <a> element's download attribute is set (for a same-origin URL) then the inline directive is ignored. Earlier versions did not match the specification and respected the header directive over the attribute. See [bug 1658877](https://bugzil.la/1658877)."



### Related:
- [changelog](https://werkzeug.palletsprojects.com/en/2.1.x/changes/?highlight=as_attachment#version-2-0-2) and https://github.com/pallets/werkzeug/issues/2149
- [changelog](https://werkzeug.palletsprojects.com/en/2.1.x/changes/?highlight=as_attachment#version-2-0-0) and https://github.com/pallets/werkzeug/issues/1869
