### ISSUE TITLE
flask's send_file parameter names have changed 

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-dashboard#142]
### Description

As of flask version 2.2.0, the `cache_timeout` parameter of `send_from_directory` is removed. It was deprecated in favor of `max_age` in version 2.0.0. Hence, if using flask >= 2.2, any dashboard that uses the `ImageViewer`, `FileList`, or `VideoViewer` modules will not display the content of the cards as expected.

### To reproduce

Run a dashboard that displays images where the flask version >= 2.2.

**Comment by bdice** [comment]
Thanks! If you can contribute a PR to fix this and bump the requirements to `flask>=2`, that'd be great.

**Comment by tcmoore3** [comment]
> Thanks! If you can contribute a PR to fix this and bump the requirements to `flask>=2`, that'd be great.

Already on it!
