### ISSUE TITLE
Figures not shown in dashboard

### ISSUE THREAD

**Issue by Charlottez112** [glotzerlab/signac-dashboard#149]
### Description

I have a workspace where each job directory has several figures saved as png files. I am able to display them in VS code, but when I tried to view them with dashboard, none of the figures was displayed correctly. They were all little question marks. 

### Error output

When I tried to open the figure in a new tab, I got the following error:
`TypeError: send_file() got an unexpected keyword argument 'cache_timeout'`

### System configuration

Please complete the following information:

 - Operating System: Linux and MacOS
 - Version of Python: 3.9.13
 - Version of signac-dashboard: '0.3.0'
 - Version of flask: '2.2.2'

**Comment by bdice** [comment]
@Charlottez112 this was fixed in #143 but has not yet been released. Would you like to assist in creating a release?

**Comment by Charlottez112** [comment]
> @Charlottez112 this was fixed in #143 but has not yet been released. Would you like to assist in creating a release?

Yes! I'd love to
