### ISSUE TITLE
Search should support both standard filters and doc filters combined

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-dashboard#25]
**[Original report](https://bitbucket.org/glotzer/signac-dashboard/issue/25) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

The search bar can currently be used for standard search and document search with (`doc:`), but not both in combination.

**Comment by csadorf** [comment]
I'm gonna tackle this.

**Comment by bdice** [comment]
@csadorf Awesome! I was hoping this could be implemented in `signac`'s simple search API directly, by offering some kind of combined syntax. Ideally the dashboard's search bar would act very similarly to the rest of the framework's search functionality.

**Comment by csadorf** [comment]
> I was hoping this could be implemented in `signac`'s simple search API directly, by offering some kind of combined syntax.

I agree, that needs to happen.

**Comment by cbkerr** [comment]
Closing since this is possible starting in [signac 1.7](https://github.com/glotzerlab/signac/releases/tag/v1.7.0).

When we make dashboard compatible with signac 2.0, you will no longer be able to use the "doc: " prefix.
