### ISSUE TITLE
The menu on the left should float

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-dashboard#26]
**[Original report](https://bitbucket.org/glotzer/signac-dashboard/issue/26) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

I think it would be great if the menu on the left would stay on left so that it is not necessary to scroll all the way up for the module selection.

**Comment by bdice** [comment]
This might not be a good idea, in retrospect. In my current project, I have more than 1 screen-height of modules, meaning that a floating left panel would not allow me to access all of them.

**Comment by csadorf** [comment]
> This might not be a good idea, in retrospect. In my current project, I have more than 1 screen-height of modules, meaning that a floating left panel would not allow me to access all of them.

Then let's close this issue.
