### ISSUE TITLE
Create project overview page

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-dashboard#27]
**[Original report](https://bitbucket.org/glotzer/signac-dashboard/issue/27) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

The dashboard menu should include a project overview page. Information I'd like to include:

* Project Schema
* Project document
* Project directory path
* Number of jobs

**Comment by cbkerr** [comment]
Since we decided against displaying the project directory path for security (https://github.com/glotzerlab/signac-dashboard/pull/110#discussion_r802231850), all of these are now implemented in #110!
