### ISSUE TITLE
video viewer bugs

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-dashboard#39]
1. https://github.com/glotzerlab/signac-dashboard/blob/79ebe3648672459ca4b07046211e941e188e9ef7/signac_dashboard/modules/video_viewer.py#L19 should probably be `poster='none'`, otherwise we get a `TypeError: join() argument must be str or bytes, not 'NoneType'` on https://github.com/glotzerlab/signac-dashboard/blob/79ebe3648672459ca4b07046211e941e188e9ef7/signac_dashboard/modules/video_viewer.py#L39

2. The dictionary returned by `make_card` should also contain the key `jobid=job._id`, otherwise the path to the video files is incorrect: `http://localhost:<port>/jobs//file/<fname>.mp4` (notice missing job hash).

**Comment by bdice** [comment]
@berceanu Can you check if the `master` branch still shows this problem? I believe this was addressed in a previous pull request https://github.com/glotzerlab/signac-dashboard/pull/34 but I have not made a release since that bugfix.

**Comment by berceanu** [comment]
`master` works ;)

**Comment by bdice** [comment]
This is resolved in `master`.
