### ISSUE TITLE
Hosting a dashboard on a webserver

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-dashboard#70]
In order to share analysis results with my team members, I would find it useful to be able to host signac dashboards on an nginx/apache web server instance hosting our domain. Is that possible/documented?

**Comment by bdice** [comment]
Hey @berceanu! Yes, this is possible. I'll add an example of how I've used the gunicorn or bjoern servers for this. Any server supporting WSGI can do this, so nginx and apache are also options.

You might read about how to enable signac-dashboard with Apache here. The dashboard is just a Flask application, so most guides that apply to Flask will also apply to signac-dashboard:
https://www.codementor.io/abhishake/minimal-apache-configuration-for-deploying-a-flask-app-ubuntu-18-04-phu50a7ft

As a disclaimer, I am not a security expert. I recommend that dashboards should be accessible only on protected internal servers, not internet-facing addresses. See also these [Security Guidelines](https://docs.signac.io/projects/dashboard/en/latest/security.html) for warnings about arbitrary code execution.

**Comment by bdice** [comment]
@berceanu There's an example of this here, using gunicorn: https://github.com/glotzerlab/signac-dashboard/tree/master/examples/wsgi

If you have any questions about how this works, just ask. 😄

**Comment by berceanu** [comment]
Thanks, that seems to work! 

What if I want to host multiple dashboards simultaneously though, at `mydomain.com/dash1`, `mydomain.com/dash2`

**Comment by bdice** [comment]
@berceanu If you’re using mod_wsgi, this might help: https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIScriptAlias.html

I googled around and it seems that WSGIScriptAlias is the best way to host an application at a subdirectory. Of course, subdomains and other ports would also work.

**Comment by berceanu** [comment]
That's awesome, thanks @bdice :)

**Comment by bdice** [comment]
@berceanu I’m glad it helped! I’ll close this for now, feel free to re-open it if you have more related questions. Also I’m interested in writing a “user story” on our website about how you use the signac framework. If you’re open to that, message me on Gitter and we can discuss! 👍

**Comment by berceanu** [comment]
I found using `nginx` to be a more robust solution for deployment.
For example, see [this guide](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04).

**Comment by csadorf** [comment]
@bdice Maybe we can add that link to the docs?

**Comment by berceanu** [comment]
So I ran into a small config problem regarding the template paths. This *only* occurs when using the `nginx`/`gunicorn` setup, as described in [gunicorn.md](https://github.com/berceanu/random-phase-approximation/blob/7428965a6fbdc4eebb78a94830d4ae4f1e732ffb/gunicorn.md). 

```
gunicorn[23713]:   File "/home/berceanu/Development/rpa/mypackage/mypackage/dipole_transitions.py", line 32
gunicorn[23713]:     "content": render_template(self.template, table=table),
gunicorn[23713]:   File "/home/berceanu/miniconda3/envs/random-phase-approximation/lib/python3.7/site-packa
gunicorn[23713]:     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
gunicorn[23713]:   File "/home/berceanu/miniconda3/envs/random-phase-approximation/lib/python3.7/site-packa
gunicorn[23713]:     return self._get_source_fast(environment, template)
gunicorn[23713]:   File "/home/berceanu/miniconda3/envs/random-phase-approximation/lib/python3.7/site-packa
gunicorn[23713]:     raise TemplateNotFound(template)
gunicorn[23713]: jinja2.exceptions.TemplateNotFound: cards/dipole_transitions.j2
gunicorn[23713]: 404 Not Found: The requested URL was not found on the server. If you entered the URL manua
```
The error involves [this dashboard file](https://github.com/berceanu/random-phase-approximation/blob/7428965a6fbdc4eebb78a94830d4ae4f1e732ffb/projects/rpa/src/dashboard.py), which uses my user-defined dashboard [module](https://github.com/berceanu/random-phase-approximation/blob/7428965a6fbdc4eebb78a94830d4ae4f1e732ffb/mypackage/mypackage/dipole_transitions.py) that depends on [this `jinja` template](https://github.com/berceanu/random-phase-approximation/blob/7428965a6fbdc4eebb78a94830d4ae4f1e732ffb/projects/rpa/src/templates/cards/dipole_transitions.j2).

**Comment by bdice** [comment]
@berceanu I would guess this issue has to do with how your paths are set up. In my understanding, you're able to make it run when calling `python dashboard.py run` but not with the WSGI application in the folder above `dashboard.py`? I would try changing `'DASHBOARD_PATHS': ['src/']` to `'DASHBOARD_PATHS': ['.']` and see what happens. Usually my custom modules live in the same folder as my dashboard and templates, so there may be a problem that I just haven't encountered before related to calling the dashboard from another directory via WSGI with custom modules/templates in different places. Let me know if you make any progress or if I should try it out locally.

**Comment by berceanu** [comment]
```
rpa
├── README.md
├── signac.rc
├── src
│   ├── dashboard.py
│   ├── init.py
│   ├── project.py
│   ├── templates
│   │   ├── cards
│   │   │   └── dipole_transitions.j2
│   └── wsgi.py
└── workspace
    ├── 03481402935f42d624064dc3ca76238f
    ├── ............................................................. 
```
So running `gunicorn --bind 0.0.0.0:5000 wsgi:dashboard` inside the `src/` folder has the problem of not finding the template, as described above.

Changing `'DASHBOARD_PATHS'` from `['src/']` to `['.']` seems to fix this problem.

**Comment by bdice** [comment]
@berceanu Fantastic -- seems like the deployed version shows the table now, which is super cool. Glad it's working, and feel free to re-open this issue if you have more questions.
