### ISSUE TITLE
filter dashboard jobs

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-dashboard#71]
I know I can search inside a dashboard, but can I select a subset of jobs to be shown by default in a particular project dashbard, based on a statepoint/doc filter?

**Comment by bdice** [comment]
I usually just use a search query for selection. To make this possible, we would probably need some mechanism for sub-selection from a JobsIterator or something like that in signac. Perhaps chaining searches with an "AND" operator could help, too.

@csadorf may have thoughts on this (but his PhD defense is tomorrow so give him time to respond).

Also, it would be possible to overwrite the "home page" of the dashboard to point to a specific search query if you're just looking to default to that query. Let me know if you're interested in this solution and I can make a minimal working example.

**Comment by berceanu** [comment]
My quick hack was to append stuff like `/search?q=astro+n` to the links in the home page, is that what you mean by "overwriting home page"?

**Comment by bdice** [comment]
@berceanu Sorry for the delay. Yes, that's a pretty good solution to just append the search query. I spent a little time experimenting with alternative solutions but didn't come up with anything much better than that. Let me know if this continues to be a challenge and we can discuss further. I'll close this issue for now.
