### ISSUE TITLE
Text box to go straight to a specific job

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-dashboard#84]
### Feature description

It would be great if there was a text box into which I could enter the first few characters of a statepoint id and go directly to that job. I can currently go to `localhost:port/jobs/abc123`, but it would be nicer if I didn't have to click in the address bar to do that.

**Comment by cbkerr** [comment]
>click in the address bar to do that

Workaround: in Firefox, Safari, and Chrome on Mac, **⌘-L** makes the address bar the focus. With a web browser remembering recent history for autocomplete, does this resolve your feature request @tcmoore3?

At the risk of adding too many keywords to the search bar, we could add it as a search with a prefix like `jobid:`.
This feature could also be added with a keyboard shortcut like in #22.

**Comment by tcmoore3** [comment]
> > click in the address bar to do that
> 
> Workaround: in Firefox, Safari, and Chrome on Mac, **⌘-L** makes the address bar the focus. With a web browser remembering recent history for autocomplete, does this resolve your feature request @tcmoore3?

That's essentially what I do now, so no improvement over the current scenario. 

> 
> At the risk of adding too many keywords to the search bar, we could add it as a search with a prefix like `jobid:`. This feature could also be added with a keyboard shortcut like in #22.

I'm OK with this idea.

While I'm OK with the `jobid:` search prefix, I'm not willing to invest the time to implement it. I am closing as stale.
