### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-dashboard#85]
### Feature description

It would be dope if searches were saved and easily accessible from the dashboard. I find myself entering fairly complicated search strings and then needing to reuse the searches. 

### Proposed solution

Having a search history in the dashboard page would be nice, and being able to somehow label searches would be a further enhancement.

### Additional context

I'm happy to try to implement this kind of feature but I really have no idea where to start.

**Comment by bdice** [comment]
@tcmoore3 Typically my browser (Firefox) remembers the search strings I have previously used. I can pull that up just by clicking in the text box where the search query is entered. Where would you propose to have the previously-used queries appear?

**Comment by tcmoore3** [comment]
Chrome does not save those searches, at least with whatever settings I have. I'm not sure exactly how I would expect it to look/work, but either a dropdown menu where the search box is, or maybe something on the side panel. 

Only my most recent search gets saved in that text box, so if I navigate away from it then I lose that string.

**Comment by csadorf** [comment]
@tcmoore3 I agree that only relying on the browser built-in search history might not be sufficient for this purpose. Can you do some general research on how such a feature could potentially be implemented in flask?

**Comment by tcmoore3** [comment]
Closing as stale; can revisit if needed.
