### ISSUE TITLE
List View / Grid View / Jobs buttons

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-dashboard#92]
### Feature description

![jobs_icon](https://user-images.githubusercontent.com/4405658/107153633-47b4fb80-6977-11eb-929d-9de08ba6c2f9.png)

In my experience, new users sometimes find the following confusing: after clicking on one job in the dashboard, they expect that clicking the List View / Grid View buttons in the top-left navbar would take them back to the list of all jobs. However, that only happens when one clicks on `Jobs` in the corner, and it is not apparent that is a clickable button.

### Proposed solution

Perhaps the Jobs button can be made more apparent, or if not, the List View / Grid View could take one back to the initial list showing all jobs?

**Comment by bdice** [comment]
Interesting idea, but I’m not sure whether this change would work. If a user performs a search, the list/grid view buttons will alternate views over the result set of jobs (not the full project). The most consistent thing would probably be to hide the view buttons when seeing a single job (and force grid view for single jobs). What do you think of that idea?

**Comment by bdice** [comment]
> However, that only happens when one clicks on Jobs in the corner, and it is not apparent that is a clickable button.

This is a menu but it’s not obvious because there are no other menu items. 😂 I would like to add some other sections like Search (a power search with all options explained), Settings, Project Info, etc.

**Comment by berceanu** [comment]
I see, so clicking on a single job is considered as doing a single-result search, that makes sense. In that case, yes, I think hiding them for single jobs and defaulting to grid would be a good approach.

**Comment by cbkerr** [comment]
Resolved in #110 by making the "views" section disappear when showing a single job.
