### ISSUE TITLE
Mobile-friendly view

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-dashboard#93]
### Feature description

It would be nice if the navbar showing the module list would be visible when browsing from a small-screen mobile device.

### Proposed solution

Perhaps it could be toggled on/off for saving screen real-estate?

**Comment by bdice** [comment]
![971E8FFE-294A-445C-A0E0-1C2479ECC15F](https://user-images.githubusercontent.com/3943761/107154484-bde63d80-6938-11eb-8a7f-87dc690e9cc1.jpeg)
How does this placement look? It would be in the folded menu that is triggered by the button in the top right.

**Comment by berceanu** [comment]
Yes that's perfect, and makind good use of the already-existing button.
